### ISSUE TITLE
Language Dropdown in Modeler 5.x

### ISSUE THREAD

**Issue by cwettstein** [FlowSquad/camunda-modeler-i18n-plugin#14]
Where can I find the language selection dropdown in Camunda Modeler 5.x? Modeler 5.x has no toolbasr anymore. 

Thanks for a hint.

**Comment by rami-nk** [comment]
The Camunda v5 compatibility branch is now merged into main. The dropdown should now be visible in your Camunda modeler v5+. I will update the image in the README.md.
