### ISSUE TITLE
Should I know how you get all string fields for translating?

### ISSUE THREAD

**Issue by gotounix** [FlowSquad/camunda-modeler-i18n-plugin#2]
I found you get translations in `client/i18n-extension/languages/en` folder, how you get these fields?

**Comment by alex-praschek** [comment]
Hi, sorry for the late reply, I did not receive a notification for your issue and therefore didn't see it :(

To find out these strings, we just print them to the console. You can find the corresponding line of code here: 
https://github.com/FlowSquad/camunda-modeler-i18n-plugin/blob/master/client/i18n-extension/translate.js#L93

Missing translations are printed to the console by default:
![image](https://user-images.githubusercontent.com/5673767/102591645-ac3fa100-4112-11eb-910c-dd3b0896de95.png)

You can open the console view by pressing F12 or choosing Window > Toggle DevTools in the menu bar.
