### ISSUE TITLE
it seems that can't support Chinese or not for version 5.11?

### ISSUE THREAD

**Issue by hustlmh** [FlowSquad/camunda-modeler-i18n-plugin#46]
hi,
I downloaded the "camunda modeler" of Windows 64-bit zip of version 5.11 from the address https://camunda.com/download/modeler/. After decompression, the program can run normally. Then I decompress the v2.0 data package and copy all of them to the “camunda-modeler-5.11.0-win-x64\resources\plugins” sub-directory of the directory of camunda moduleder.exe . Enter the interface and select "Simplified Chinese" and reopen it. It can be seen that only about 5% of the entire interface has been translated into Chinese, and the rest is still English (default). But if I repeat the above steps to select "Deutsch", I can see that the case seems better, but also not the entire interface content can be translated. 
Could you tell me What did I miss or how to fix it ?

 Thank you!
 Regards

![1](https://github.com/Miragon/camunda-modeler-i18n-plugin/assets/53802172/f376ccd3-1071-4fc1-abea-b275f4c450e0)
![2](https://github.com/Miragon/camunda-modeler-i18n-plugin/assets/53802172/5c7ad1f8-cd1b-4436-9bac-d8bc4b9ae868)

**Comment by rami-nk** [comment]
Hey @hustlmh,
thank you for your issue.
As far as I'm concerned the simplified Chinese does not feature so many translation keys in our application. That's the reason why you are not seeing much. You can have a look at https://github.com/Miragon/camunda-modeler-i18n-plugin/tree/develop/client/bpmnjs-i18n-extension/languages/zh-Hans to have a look at all the currently available translation keys. Feel free to extend this collection and create a PR for it. We'd definitely have a look at it!
Also, as far as I'm concerned the menu bar that you are presenting in your first screenshot is not part of the plugins responsibility.
