### ISSUE TITLE
language.changed is not a registered action

### ISSUE THREAD

**Issue by JAVPHP** [FlowSquad/camunda-modeler-i18n-plugin#5]
language.changed is not a registered action
    at o (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:257:9)
    at error (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:167:10)
    at trigger (webpack:///src/app/tabs/bpmn/BpmnEditor.js:617:40)
    at triggerAction (webpack:///src/app/tabs/MultiSheetTab.js:259:18)
    at triggerAction (webpack:///src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack:///src/app/App.js:1719:15)
    at fn (webpack:///src/app/App.js:2244:19)
    at file:///D:/dev/workspace/camunda/modeler/modeler/resources/app.asar/public/bundle.js:65:127778
    at exec (webpack:///src/app/AppParent.js:76:11)
    at EventEmitter.emit (events.js:203:13) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]

**Comment by alex-praschek** [comment]
Hi, what version of Camunda Modeler are you using?

**Comment by pvana** [comment]
Hi, we have the same issue as mentioned above. FYR the Camunda Modeler version: 4.7.0. Would be possible to advise?

**Comment by alex-praschek** [comment]
I'll take a look, thanks for reporting!

**Comment by alex-praschek** [comment]
In version 4.7.0 of Camunda Modeler there was a [change](https://github.com/camunda/camunda-modeler/pull/2155) that prevents our way of saving the chosen language from working. We are currently looking for an alternative way to achieve this. Please give us a few days to resolve this. Thanks!

**Comment by Suoson** [comment]
Hello, are there any news regarding this topic?
I can confirm that it does not work with the newest Version 4.8.1, still the same error.
After a brief call to Camunda Customer Service, this Plugin is the officially intended way to translate the modeler.
They were not aware of it not working.
Just asking, currently looking into using modeler in german.

**Comment by dominikhorn93** [comment]
Hi @Suoson,
I will fix this until the end of the week.
Sorry this has been left for so long!

**Comment by dominikhorn93** [comment]
Hi @Suoson & @pvana , the release is built. After a language change, the modeler must now be restarted once. Furthermore, the language selection is now in the toolbar. This was necessary due to changes in the core of the modeler.
