### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by JAVPHP** [FlowSquad/camunda-modeler-i18n-plugin#7]
![image](https://user-images.githubusercontent.com/48326762/127947137-9dc6c4a7-354e-4f88-bec8-0bc11fc8122a.png)

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\dev\\node\\program\\node.exe',
1 verbose cli   'D:\\dev\\node\\program\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--scripts-prepend-node-path=auto'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle camunda-modeler-i18n-plugin@1.1.0~prebuild: camunda-modeler-i18n-plugin@1.1.0
6 info lifecycle camunda-modeler-i18n-plugin@1.1.0~build: camunda-modeler-i18n-plugin@1.1.0
7 verbose lifecycle camunda-modeler-i18n-plugin@1.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle camunda-modeler-i18n-plugin@1.1.0~build: PATH: D:\dev\node\program\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\dev\workspace\camunda\modeler\camunda-modeler-i18n-plugin-develop\camunda-modeler-i18n-plugin-develop\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;D:\dev\maven\program\bin;D:\dev\tortoise\program\bin;D:\dev\git\program\Git\cmd;D:\dev\mysql\mysql-5.7.32-winx64\bin;D:\dev\node\program\;D:\dev\sdk\flutter\bin;D:\dev\gradle\gradle-6.8.3\bin;D:\dev\sdk\java\jdk\bin;D:\dev\sdk\java\jdk\jre\bin;D:\dev\sdk\flutter\.pub-cache\bin;D:\dev\sdk\flutter\bin\cache\dart-sdk\bin;C:\Users\87761\AppData\Local\Microsoft\WindowsApps;D:\other\zip\;D:\dev\idea\program\IntelliJ IDEA 2020.2\bin;;;D:\dev\vscode\program\Microsoft VS Code\bin
9 verbose lifecycle camunda-modeler-i18n-plugin@1.1.0~build: CWD: D:\dev\workspace\camunda\modeler\camunda-modeler-i18n-plugin-develop\camunda-modeler-i18n-plugin-develop
10 silly lifecycle camunda-modeler-i18n-plugin@1.1.0~build: Args: [ '/d /s /c', 'run-s bundle' ]
11 silly lifecycle camunda-modeler-i18n-plugin@1.1.0~build: Returned: code: 1  signal: null
12 info lifecycle camunda-modeler-i18n-plugin@1.1.0~build: Failed to exec build script
13 verbose stack Error: camunda-modeler-i18n-plugin@1.1.0 build: `run-s bundle`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\dev\node\program\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (D:\dev\node\program\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid camunda-modeler-i18n-plugin@1.1.0
15 verbose cwd D:\dev\workspace\camunda\modeler\camunda-modeler-i18n-plugin-develop\camunda-modeler-i18n-plugin-develop
16 verbose Windows_NT 10.0.19042
17 verbose argv "D:\\dev\\node\\program\\node.exe" "D:\\dev\\node\\program\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--scripts-prepend-node-path=auto"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error camunda-modeler-i18n-plugin@1.1.0 build: `run-s bundle`
22 error Exit status 1
23 error Failed at the camunda-modeler-i18n-plugin@1.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by JAVPHP** [comment]
![image](https://user-images.githubusercontent.com/48326762/127947325-19054f13-61e6-4af1-ac34-66dcc3a1da4b.png)

**Comment by dominikhorn93** [comment]
Hi @JAVPHP,

run `npm install` an give it a try.
In windows the build crashed due to a missing react-dom dependency.
